// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package team4188_2013.commands;
import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.image.ParticleAnalysisReport;
import team4188_2013.Robot;
/**
 *@author Tobore Tasker
 * Used for pan/tilt for auto-aim, only ever panned. 
 * refer to Java doc for help with interfacing with servos
 */
public class  PanServo extends Command {
        private ParticleAnalysisReport target;
    final static double 
            xMin = 0,
            xMax = 58,
            yMin = 0,
            yMax = 100,
            TOLERANCE = 1.0,
            //BoardDistance = 60.0, //60.0 inches 
            X_RANGE = 116;
  //  static double position = 90.0;
    
    boolean isTargeted = false, aimed = false;
    double 
        targetDistance = 0.0, angleX = 0.0, angleY = 0.0;
    int input = 0;
    Timer timer = new Timer();
  
    public PanServo() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        System.out.println("Pan Initializing");
        aimed = false;
        isTargeted = false;
        angleX = 0.0;
        angleY = 0.0;
        //position = 90; //start at 90 degrees
         //go to starting position
       // panX.setAngle(input);
        
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
        // panX.goToPosition(oi.getJoystick().getX());
         //System.out.println(oi.getJoystick().getY());
         //panY.goToPosition(-oi.getJoystick().getY());
         
        
         if(Robot.vision.getReports())
         {   
            //SmartDashboard.putInt("Targets", vision.getFound());
            //TargetDistance = vision.getDistance();
            isTargeted = Robot.vision.getTargeted();
            System.out.println("isTargeted: " + isTargeted);
            if(isTargeted == false){
               // SmartDashboard.putString("Pan", "Looking...");
                System.out.println("Looking for targets...");
                angleX = 0.0;
                angleY = 0.0;
                targetDistance = 0.0;
            }
            else{
               System.out.println("Aiming...");
               target = Robot.vision.getTopTarget();
               targetDistance = Robot.vision.getDistance();
               angleX = Robot.vision.calculateHorizontalAngle(target, targetDistance);
               angleY = Robot.vision.calculateTiltAngle(target, targetDistance);
                isAimed();
                //System.out.println("Angle X: "+ angleX);
               System.out.println("Angle Y: " + angleY);
                if(aimed == false)
                {
                 aim();
                }
                //TargetDistance = 0.0;
                //panY.setAngle(((angleY)+1)/2);
               // System.out.println("Titling");
                //panX.setAngle(((angleX)+1)/4);
                //System.out.println("panning..");
               // SmartDashboard.putString("pan", "Panning");
            }        
            /*
            for(int i = 0; i < 18; i++)
            {
                System.out.println(input);
                panX.goToAngle(input);
                input += 10;
                timer.delay(1);
            }
            */
        }
    }
    
    private void aim(){
       // double move = 0;
        //double servoAngle = panX.getAngle();
        //double servoPos = panX.get();
        /*
        vision.getReports();
        target = vision.getTopTarget();
        TargetDistance = vision.getTopDistance();      
        angleX = vision.calculateHorizontalAngle(target, TargetDistance);
       */
        //angleX = getAverageAngle();
       // System.out.println("Angle: " + angleX);
       // move = angleX/5;
    //    drivetrain.panX.goToAngle(drivetrain.getPosition() - (move));
        
        //vision.panX.goToAngle(position - (move/2));
       // System.out.println("Panning Angle: "+ servoAngle);
        //System.out.println("Panning Position: "+ servoPos);
      //  turnXDegrees(vision.calculateHorizontalAngle(target, targetDistance));
        aimed = true;
        //drivetrain.setPosition(drivetrain.getPosition()-move);
       // position = vision.getPosition(); //- (move) - move/3;
       // System.out.println("Position: " + drivetrain.getPosition());
    }
    private double getAverageAngle(){
        double average = 0, a = 0, b = 0, c = 0;
        Robot.vision.getReports();
        target = Robot.vision.getTopTarget();
        targetDistance = Robot.vision.getDistance();
        a = Robot.vision.calculateHorizontalAngle(target, targetDistance);
        /*
        vision.getReports();
        target = vision.getTopTarget();
        TargetDistance = vision.getTopDistance();
        b = vision.calculateHorizontalAngle(target, TargetDistance); 
        vision.getReports();
        target = vision.getTopTarget();
        TargetDistance = vision.getTopDistance();
        c = vision.calculateHorizontalAngle(target, TargetDistance); 
        */
        average = (a );
        System.out.println("Average Horizontal Angle: " + average );
        return average;
    }
    private void isAimed(){
        //double sAngle = panX.getAngle();
        //double diff = Math.abs(sAngle - angleX);
        System.out.println("AngleX: " + angleX);
        if((Math.abs(angleX) >= TOLERANCE)){
           // System.out.println("Angle Diff: " + diff);
            aimed = false;
        }
        else{
            aimed = true;
        }
        
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }
    // Called once after isFinished returns true
    protected void end() {
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
