// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package team4188_2013.subsystems;
import team4188_2013.RobotMap;
import team4188_2013.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.Encoder.PIDSourceParameter;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
/**
 *@author Tobore Tasker
 */
public class Shooter extends Subsystem {
    private PIDController tiltPID;
    Timer timer;
    private boolean timerRunning = false;    
    public boolean 
            isOn = false,
            isLoaderExtended = false,
            isPusherExtended = false;
    public double increment = 0.0;
    static double //for testing, improper format for variables
        MAX_VOLT_FIRST = 12.0,
        MAX_VOLT_SECOND = 12.0,
        MAX_VOLT_TILT = 12.0, 
        P = 0.025,
        I = 0.000,
        D = 0.000;
    final static double 
        //MAX_VOLT_FIRST = 12.0,
        //MAX_VOLT_SECOND = 12.0,
       // MAX_VOLT_TILT = 12.0,    
        FORWARD = 1.0, 
        OFF = 0.0,
        M = -2.2117,
        B = 160.22,
        tiltTolerance = 5.0,
//        P = 0.025, 
//        I = 0.000, 
//        D = 0.0,     
        PID_LOOP_TIME = .05,
        SETTLED_TIME = 1.0;            ;
    private static final double PNEUMATIC_DELAY_SECONDS = 0.1;
    double maxVoltageSecondWheel = MAX_VOLT_SECOND;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    AnalogChannel tiltPot = RobotMap.shootertiltPot;
    CANJaguar firstWheel = RobotMap.shooterfirstWheel;
    CANJaguar secondWheel = RobotMap.shootersecondWheel;
    CANJaguar tilt = RobotMap.shootertilt;
    DoubleSolenoid feederSol = RobotMap.shooterfeederSol;
    DoubleSolenoid pushSol = RobotMap.shooterpushSol;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        setDefaultCommand(new ManualTilt());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
        
    }
    public void init(){
        SmartDashboard.putNumber("First", MAX_VOLT_FIRST);
        SmartDashboard.putNumber("Second", MAX_VOLT_SECOND);
        SmartDashboard.putNumber("Tilt", MAX_VOLT_TILT);
        SmartDashboard.putNumber("shooterP", P);
        SmartDashboard.putNumber("shooterI", I);
        SmartDashboard.putNumber("shooterD", D);
        pushDoNothing();
        loaderDoNothing();
        try{
            firstWheel.configMaxOutputVoltage(MAX_VOLT_FIRST);
            secondWheel.configMaxOutputVoltage(MAX_VOLT_SECOND);
            tilt.configMaxOutputVoltage(MAX_VOLT_TILT);
            tilt.configNeutralMode(CANJaguar.NeutralMode.kBrake);
            firstWheel.configNeutralMode(CANJaguar.NeutralMode.kCoast);
            secondWheel.configNeutralMode(CANJaguar.NeutralMode.kCoast);
           } catch (CANTimeoutException ex) {ex.printStackTrace();}
        tiltPID = new PIDController(P,I,D,tiltPot,tilt,PID_LOOP_TIME);
        tiltPID.setInputRange(0, 180.0);
        tiltPID.setOutputRange(-0.6, 0.6);    
        timer = new Timer();        
    }
    public void setShooterPID(){
        P = SmartDashboard.getNumber("shooterP");
        I = SmartDashboard.getNumber("shooterI");
        D = SmartDashboard.getNumber("shooterD");
     }
    public void setMaxVoltages(){
        MAX_VOLT_FIRST = SmartDashboard.getNumber("First");
        MAX_VOLT_SECOND = SmartDashboard.getNumber("Second");
        MAX_VOLT_TILT = SmartDashboard.getNumber("Tilt");
        try{
            firstWheel.configMaxOutputVoltage(MAX_VOLT_FIRST);
            secondWheel.configMaxOutputVoltage(MAX_VOLT_SECOND);
            tilt.configMaxOutputVoltage(MAX_VOLT_TILT);    
           } catch (CANTimeoutException ex) {ex.printStackTrace();}            
    }    
    public boolean autoTilt(double angle){
        double potValue = 0.0;
        if(!tiltPID.isEnable())tiltPID.enable();
        potValue = angle * M + B;
        tiltPID.setSetpoint(potValue);
        if(thereYet(potValue)) {
            tiltPID.disable();
            return true;
        }
        return false;        
    }
   public boolean thereYet(double target) 
   {
        if(onTarget(target) && !timerRunning) 
        {
            timer.start();
            timerRunning = true;
        }
        else if (!onTarget(target) && timerRunning)
        {
            timer.stop();
            timer.reset();
            timerRunning = false;
        }
        return timer.get() >= SETTLED_TIME;
    }    
   public boolean onTarget(double potValue){
       boolean toReturn = false;
       double difference = 0;
       difference = Math.abs(potValue - getTiltVoltage());
       
       if(difference > tiltTolerance){
           toReturn = true;
       }
       else{
           toReturn = false;
       }
       return toReturn;
       
   }
    public void setVoltageFirstWheel(double adjust){
        try{
        firstWheel.configMaxOutputVoltage(adjust);
        } catch (CANTimeoutException ex) {ex.printStackTrace();} 
        maxVoltageSecondWheel = adjust;
    }
    public double getMaxVoltageFirstWheel(){
        return maxVoltageSecondWheel;
    }
    public void shooterOn(double modifier){
        try{
            firstWheel.setX(FORWARD * modifier);
            secondWheel.setX(FORWARD * modifier);
          } catch (CANTimeoutException ex) {ex.printStackTrace();}  
        isOn = true;
        System.out.println("Shooter On!");
    }
    public void shooterOff(){
        try{
            firstWheel.setX(OFF);
            secondWheel.setX(OFF);
          } catch (CANTimeoutException ex) {ex.printStackTrace();} 
        isOn = false;
        increment = 0.0;
        System.out.println("Shooter Off!");
    }
    public boolean isOn(){
        return isOn;
    }    
    public void manualAim(double input){
        if(tiltPID.isEnable())tiltPID.disable();
        try {
            tilt.setX(input);   
        } catch (CANTimeoutException ex) {ex.printStackTrace();}
    }    
    public void adjustSpeed(double throttle){
            try{
            firstWheel.setX(FORWARD * throttle);
            secondWheel.setX(FORWARD * throttle);
          } catch (CANTimeoutException ex) {ex.printStackTrace();} 
        
    }
    public double getTiltVoltage(){
        return tiltPot.getVoltage();
    }
    public double getTiltValue(){
        return tiltPot.getValue();
    }
    public double getCalibrateValue(){
        return Math.abs(tiltPot.getValue() - 370);
    }
    //returns true when limit swich is pressed
    public boolean getBottowSw(){
        boolean switchedBottom = false;
        try {
            switchedBottom = tilt.getReverseLimitOK();
        } catch (CANTimeoutException ex) {ex.printStackTrace();}
        return !switchedBottom;
    }
    public boolean getTopSw(){
        boolean switchedTop = false;
        try {
            switchedTop = tilt.getForwardLimitOK();
        } catch (CANTimeoutException ex) {ex.printStackTrace();}      
        return !switchedTop;
    }
    public void extendLoader(){
        feederSol.set(DoubleSolenoid.Value.kForward);
        Timer.delay(PNEUMATIC_DELAY_SECONDS);
        feederSol.set(DoubleSolenoid.Value.kOff);
        isLoaderExtended = true;
    }
    public void retractLoader(){
        feederSol.set(DoubleSolenoid.Value.kReverse);
        Timer.delay(PNEUMATIC_DELAY_SECONDS);
        feederSol.set(DoubleSolenoid.Value.kOff);
        isLoaderExtended = false;
    }
    public void extendPusher(){
        pushSol.set(DoubleSolenoid.Value.kForward);
        Timer.delay(PNEUMATIC_DELAY_SECONDS);
        pushSol.set(DoubleSolenoid.Value.kOff);
        isPusherExtended = true;
    }
    public void retractPusher(){
        pushSol.set(DoubleSolenoid.Value.kReverse);
        Timer.delay(PNEUMATIC_DELAY_SECONDS);
        pushSol.set(DoubleSolenoid.Value.kOff);
        isPusherExtended = false;
    }
    public boolean isPusherExtended(){
        return isPusherExtended;
    }
    public boolean isLoaderExtended(){
        return isLoaderExtended;
    }
    public void loaderDoNothing(){
       feederSol.set(DoubleSolenoid.Value.kOff);
    }
    public void pushDoNothing(){
        pushSol.set(DoubleSolenoid.Value.kOff);
    }
}
