// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
package org.usfirst.frc4188.ColumbusCorpsBot;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.can.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;
/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Gyro drivetrainGyro1;
    public static boolean fOM=false;
    public static CANJaguar drivetrainfrontLeftMotor;
    public static CANJaguar drivetrainrearLeftMotor;
    public static CANJaguar drivetrainfrontRightMotor;
    public static CANJaguar drivetrainrearRightMotor;
    public static CorpsRobotDrive Drive;
    public static Timer timer;
    public static PIDController gyroPID;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
        public static final double 
            gyroTOLERANCE = 0.5,
            Pg = 0.006, 
            Ig = 0.0002, 
            Dg = 0.0,     // LEAVE THESE CONSTANTS ALONE!
            PID_LOOP_TIME = .05,
            SETTLED_TIME = 1.0; 
    public static void init() {
        timer = new Timer();
        gyroPID = new PIDController(Pg,Ig,Dg,drivetrainGyro1,Drive,PID_LOOP_TIME);
        gyroPID.setInputRange(-90.0, 90.0);
        gyroPID.setOutputRange(-0.6, 0.6);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainGyro1 = new Gyro(1);
	LiveWindow.addSensor("Drivetrain", "Gyro 1", drivetrainGyro1);
        try { 
            drivetrainfrontLeftMotor = new CANJaguar(2);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
	
        
        try { 
            drivetrainrearLeftMotor = new CANJaguar(3);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
	
        
        try { 
            drivetrainfrontRightMotor = new CANJaguar(4);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
	
        
        try { 
            drivetrainrearRightMotor = new CANJaguar(6);
        } catch (CANTimeoutException ex) {
            ex.printStackTrace();
        }
	
        
        Drive = new CorpsRobotDrive(drivetrainfrontLeftMotor, drivetrainrearLeftMotor,
              drivetrainfrontRightMotor, drivetrainrearRightMotor);
	
        Drive.setSafetyEnabled(false);
        Drive.setExpiration(0.1);
        Drive.setSensitivity(0.5);
        Drive.setMaxOutput(1.0);
        Drive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        Drive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
